# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trustyAMD64"
  config.vm.provision "shell", path: "setup.sh"

  config.vm.define "rgw" do |rgw|
    rgw.vm.network :forwarded_port, guest: 80, host: 7080
    rgw.vm.network :private_network, ip: "192.168.37.10"
    rgw.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
    end
  end

  config.vm.define "mac0" do |mac0|
    mac0.vm.network :forwarded_port, guest: 80, host: 8082
    mac0.vm.network :private_network, ip: "192.168.33.12"
    mac0.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
    end
  end


  config.vm.define "keystone" do |keystone|
    keystone.vm.network :forwarded_port, guest: 80, host: 8081
    keystone.vm.network :private_network, ip: "192.168.33.11"
    keystone.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
    end
  end

  config.vm.define "shiv0" do |shiv0|
    shiv0.vm.network :forwarded_port, guest: 80, host: 8091
    shiv0.vm.network :private_network, ip: "192.168.35.13"
    shiv0.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
    end
  end

  config.vm.define "shiv1" do |shiv1|
    shiv1.vm.network :forwarded_port, guest: 80, host: 8092
    shiv1.vm.network :private_network, ip: "192.168.35.14"
    shiv1.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
    end
  end

  config.vm.define "rgarg0" do |rgarg0|
    rgarg0.vm.network :forwarded_port, guest: 80, host: 8093
    rgarg0.vm.network :private_network, ip: "192.168.34.21"
    rgarg0.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
    end
  end

  config.vm.define "rgarg1" do |rgarg1|
    rgarg1.vm.network :forwarded_port, guest: 80, host: 8094
    rgarg1.vm.network :private_network, ip: "192.168.34.22"
    rgarg1.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--memory", "8192"]
      vb.customize ["modifyvm", :id, "--cpus", "8"]
    end
  end

end
